---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-ingress-role
  namespace: sock-shop
rules:
  - apiGroups: [""]
    resources: ["configmaps","endpoints","pods","secrets"]
    verbs: ["get"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","update"]
    resourceNames: ["ingress-controller-leader"]
  
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]

# used this link to build: https://kubernetes.github.io/ingress-nginx/deploy/rbac/