---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-ingress-role-binding
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
    namespace: sock-shop
roleRef:
  kind: Role
  name: nginx-ingress-role
  apiGroup: rbac.authorization.k8s.io