---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-clusterrole
rules:
  - apiGroups: [""]
    resources: ["configmaps","endpoints","pods","secrets","services","nodes"]
    verbs: ["get","list", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses","ingressclasses"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["update"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list","watch"]



# used this link to build: https://kubernetes.github.io/ingress-nginx/deploy/rbac/